version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yii2_photo_review

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yii2_photo_review
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./public:/var/www/html
    ports:
      - 80:80